// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqW2s3PC9jzAOou80dggvXCATSEeTKTGY',
    appId: '1:950090189458:web:949c08d59839cbda08f44b',
    messagingSenderId: '950090189458',
    projectId: 'culinary-app-c7b0c',
    authDomain: 'culinary-app-c7b0c.firebaseapp.com',
    storageBucket: 'culinary-app-c7b0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOqlu3XNFeVHPH_bHcApl-iYzzz9xeHEs',
    appId: '1:950090189458:android:f522d119b43fb96a08f44b',
    messagingSenderId: '950090189458',
    projectId: 'culinary-app-c7b0c',
    storageBucket: 'culinary-app-c7b0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIR2YUvGnOJv9SGj6TgDFE6JjnrRks5Cc',
    appId: '1:950090189458:ios:670e61c14c85faf108f44b',
    messagingSenderId: '950090189458',
    projectId: 'culinary-app-c7b0c',
    storageBucket: 'culinary-app-c7b0c.appspot.com',
    iosBundleId: 'com.example.culinaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIR2YUvGnOJv9SGj6TgDFE6JjnrRks5Cc',
    appId: '1:950090189458:ios:f421d71ff2c6e59008f44b',
    messagingSenderId: '950090189458',
    projectId: 'culinary-app-c7b0c',
    storageBucket: 'culinary-app-c7b0c.appspot.com',
    iosBundleId: 'com.example.culinaryApp.RunnerTests',
  );
}
